config/routes.rb
Manage::Application.routes.draw do

  devise_for :logins
  resources :users do
    resources :infos
  end

  get "collective_consumption" => "infos#collective_consumption"
  get "recharge" => "infos#recharge"
  get "chart" => "infos#chart"
  get "search_by_date" => "infos#search_by_date"
  get "transfer" => "infos#transfer"

  root :to => "users#index"

end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :user
end

app/models/login.rb
class Login < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :infos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/infos_controller.rb
# encoding: utf-8
class InfosController < ApplicationController
  before_filter :authenticate_login!
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  def transfer
    if(!params["from"] && !params["to"])
      @all_users = ""
      users = User.find(:all)
      users.each do |user|
        @all_users += "<option>#{user.name}</option>"
      end
      render "transfer"
    else
      from = params["from"]
      to = params["to"]
      from_money = ("-" + params["money"]).to_f
      to_money =  params["money"].to_f
      condiditon = "('" + from + "','" + to + "')"
      users = User.find_by_sql ["select * from users where name in #{condiditon}"]
      users.each do |user|
        info = Info.new
        info.user_id = user.id
        if(user.name == from)
          info.money = from_money
        else
          info.money = to_money
        end
        info.date = Time.now
        info.address = "由#{from}转账给#{to}"
        info.save
      end
      redirect_to "/users"
    end
  end

  def search_by_date
    result = {}
    date = []
    money = []
    start_time = (Time.now.utc - 30.days).to_s.split(" ")[0]
    end_time = Time.now.utc.to_s.split(" ")[0]

    infos = Info.find_by_sql ["select sum(money) as money,date(date) as date from infos where date > ? and date < ? and money < ? and address NOT like '% 转账%' group by date(date)",start_time,end_time,0]
    infos_count = infos.count
    infos.each do |info|
      if (infos_count < 11)
        date << info.date.to_s.gsub("-",".")
      else
        date << info.date.to_s.gsub("-",".").split(".").last
      end
      money << info.money.to_s.gsub("-","").to_i
    end
    result["date"] = date
    result["money"] = money

    puts result
    respond_to do |format|
      format.js { render :json => result }
    end
  end

  def chart
    render "chart"
  end

  def recharge
    puts params
    user_id = params["user_id"]
    if(params["money"])
      money = params["money"].to_i
      if(money.to_s.include?("-"))
        money *= -1
      end
      info = Info.new
      info.user_id = user_id
      info.money = money
      info.date = Time.now
      info.address = "充值"
      info.save
      redirect_to "/users"
    else
      @user = User.find user_id
      render "recharge"
    end
  end

  def collective_consumption
    if(!params["user_ids"])
      @users = User.find(:all)
      render "collective_consumption"
    else
      user_ids = params["user_ids"]
      money = params["money"].to_f
      request_time = params["time"]

      if (request_time == "")
        time = Time.now
      else
        time = DateTime.parse(request_time)
      end

      if(!money.to_s.include?("-"))
        money *= -1
      end
      percentmoney = (money/user_ids.count).round(2)
      user_ids.each do |user_id|
        info = Info.new
        info.user_id = user_id.to_i
        info.money = percentmoney
        info.date = time
        info.address = params["address"]
        info.save
      end
      redirect_to "/users"
    end
  end

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @user= User.find(params[:user_id])
    @info = Info.new()
    @info.user_id = params[:user_id]
    @info.money = params[:info][:money]
    @info.date = params[:info][:date]
    @info.address = params[:info][:address]
    @info.save
    redirect_to @user

    #respond_to do |format|
    #  if @info.save
    #    format.html { redirect_to @info, notice: 'Info was successfully created.' }
    #    format.json { render action: 'show', status: :created, location: @info }
    #  else
    #    format.html { render action: 'new' }
    #    format.json { render json: @info.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:user_id, :money, :date, :address)
    end
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
  before_filter :authenticate_login!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    #@users = User.all
    @users = User.find_by_sql ["SELECT users.id,users.phone,users.name,SUM(infos.money) as money from users left JOIN infos on users.id = infos.user_id group by users.name order by users.id"]
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to "/users", notice: "新成员添加成功" }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "成员信息更新成功" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      puts "======== set user ========"
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      puts "======= user params ========="
      params.require(:user).permit(:name, :phone)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>hello rails !</h1>

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :money %><br>
    <%= f.number_field :money %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/chart.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<!--已经在application.js中控制-->
<!--<script src="/assets/javascripts/highcharts.js?body=1" type="text/javascript"></script>-->
<!--<script src="/assets/javascripts/exporting.js?body=1" type="text/javascript"></script>-->

<div id="chart" style="margin: 0 auto"></div>

<script type="text/javascript">
    $( document ).ready(function() {
        $.ajax({
            type: "GET",
            url: '/search_by_date',
            dataType: "json",
            success: function(data) {
                console.log(data);
                $('#chart').highcharts({
                    chart:{
                        type: 'spline',
                        backgroundColor: '#eee',
                        reflow:true
                    },
                    title: {
                        text: '最近30天消费情况',
                        x: -20 //center
                    },
//                    subtitle: {
//                        text: '最近30天消费情况',
//                        x: -20
//                    },
                    xAxis: {
                        categories: data.date
                    },
                    yAxis: {
                        title: {
                            text: 'RMB'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        valueSuffix: ''
                    },
//                    legend: {
//                        layout: 'vertical',
//                        align: 'right',
//                        verticalAlign: 'middle',
//                        borderWidth: 0
//                    },
                    series: [{
                        name: '金额',
                        data: data.money
                    }]
                });
            }
        });
    });
</script>

app/views/infos/collective_consumption.html.erb
<h1>集体消费</h1>
<div>
  <%= form_tag "/collective_consumption", :method => :get do %>
      <% @users.each do |user| %>
          <%= check_box_tag 'user_ids[]', user.id %><%= user.name %>
      <% end %>

      <div class="field">
          <%= field_set_tag do %>
              <p></p>
              金额：<p><%= text_field_tag 'money' %></p>
          <% end %>

          <%= field_set_tag do %>
              <p></p>
              日期：<p><%= text_field_tag 'time' %></p>
          <% end %>

          <%= field_set_tag do %>
              <p></p>
              描述：<p><%= text_field_tag 'address' %></p>
          <% end %>
      </div>

      <%= button_tag "消费", data: { confirm: '确认消费？' } %>
  <% end %>
</div>

<!-- </br>
</br>
<button class="test" name="submit" type="submit" value="提交1">test</button>
<script>
  $(".test").click(function(){
      var user_ids = [];

      var inputs = $("input:checked");
      var j = inputs.length;

      for (var i=0;i<j;i++){
         console.log(inputs[i].value);
         user_ids.push(inputs[i].value);
      };

      var money = $("#money").val();

      var data = {
          'user_ids': user_ids,
          'money': money
      };

      $.ajax({
          type: "GET",
          url: "/collective_consumption",
          data : data,
          dataType: "json"
      });
      alert("ok");
  });
</script> -->

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<h1>Listing infos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Money</th>
      <th>Date</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.user_id %></td>
        <td><%= info.money %></td>
        <td><%= info.date %></td>
        <td><%= info.address %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/recharge.html.erb
<h1>充值</h1>
<br>
编号：<%= @user.id %>
<br>
姓名：<%= @user.name %>
<br>
电话：<%= @user.phone %>

<br>
<br>

<div>
  <%= form_tag "/recharge", :method => :get do %>
      <%= hidden_field_tag 'user_id', @user.id %>
      <p><%= text_field_tag 'money' %></p>
      <%= button_tag "充值", data: { confirm: '确认充值？' } %>
  <% end %>
</div>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @info.user_id %>
</p>

<p>
  <strong>Money:</strong>
  <%= @info.money %>
</p>

<p>
  <strong>Date:</strong>
  <%= @info.date %>
</p>

<p>
  <strong>Address:</strong>
  <%= @info.address %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/infos/transfer.html.erb
<h1>转账</h1>
<div>
  <%= form_tag "/transfer", :method => :get do %>
      <%= select_tag "from", @all_users.html_safe %>
      =>
      <%= select_tag "to", @all_users.html_safe %>
      <div class="field">
        <%= field_set_tag do %>
            <p></p>
            金额：<p><%= text_field_tag 'money' %></p>
        <% end %>
      </div>
      <%= button_tag "转账", data: { confirm: '确认转账？' } %>
  <% end %>
</div>

app/views/layouts/_login_widget.html.erb
<% if login_signed_in? %>
    <p>Welcome <%= current_login.email %></p>
    <%= link_to 'logout', destroy_login_session_path, :method => :delete %>
<% else %>
    <p>You are not signed in.</p>
    <%= link_to 'login', new_login_session_path %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<!--<nav class="navbar navbar-inverse navbar-fixed-top">-->
  <!--<div class="container">-->
    <!--<div class="navbar-header">-->
      <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
        <!--<span class="sr-only">Toggle navigation</span>-->
        <!--<span class="icon-bar"></span>-->
        <!--<span class="icon-bar"></span>-->
        <!--<span class="icon-bar"></span>-->
      <!--</button>-->
      <!--<%= link_to 'Home', root_path, class: 'navbar-brand' %>-->
    <!--</div>-->
    <!--<div class="collapse navbar-collapse">-->
      <!--<ul class="nav navbar-nav">-->
        <!--<%= render 'layouts/navigation_links' %>-->
      <!--</ul>-->
    <!--</div>-->
  <!--</div>-->
<!--</nav>-->

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Manage" %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body style="background-color: #eee;">

    <header>
      <%= render 'layouts/navigation' %>
      <!--已经在application.js中控制-->
      <!--<script type="text/javascript" src="http://www.see-source.com/bootstrap/js/jquery.js"></script>-->
      <!--<script type="text/javascript" src="http://www.see-source.com/bootstrap/js/bootstrap-dropdown.js"></script>-->
    </header>

    <main role="main">
      <% if login_signed_in? %>
          <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color: #000;">
            <div class="navbar-header" style="float: left;margin-left: 6.5%;margin-top: 1%;font-size: large">
              <span class="total" style="color: #ffffff;">Admin</span>
            </div>
            <div class="navbar-header" style="float: right;margin-right: 2%;margin-top: 1%;">



              <div class="dropdown user-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="text-decoration: none;color: #ffffff;"><%= current_login.email %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="/logins/sign_out" class="dropdown-toggle" data-toggle="dropdown" data-method="delete" rel="nofollow">
                      <i class="glyphicon glyphicon-log-out" style="width: 2em;"></i>退出
                    </a>
                  </li>
                </ul>
              </div>

            </div>
          </nav>
          <div class="container-fluid" style="margin-top: 50px">
            <div class="row-fluid">
              <div class="span2">
                <div id="sidebar-wrapper" style="width: 18%;float: left;">
                  <ul class="sidebar-nav">
                    <li>
                      <a href="/users"><span class="glyphicon glyphicon-list" style="width: 3em;"></span>成员列表</a>
                    </li>
                    <li>
                      <a href="/chart"><span class="glyphicon glyphicon-picture" style="width: 3em;"></span>图表</a>
                    </li>
                    <% if current_login.id == 1 %>
                    <li>
                      <a href="/users/new"><span class="glyphicon glyphicon-user" style="width: 3em;"></span>添加成员</a>
                    </li>
                    <li>
                      <a href="/collective_consumption"><span class="glyphicon glyphicon-usd" style="width: 3em;"></span>集体消费</a>
                    </li>
                    <li>
                      <a href="/transfer"><span class="glyphicon glyphicon-transfer" style="width: 3em;"></span>转账</a>
                    </li>
                    <% end %>
                    <li>
                      <a href="#"><span class="glyphicon glyphicon-wrench" style="width: 3em;"></span>开发中..</a>
                    </li>
                  </ul>
                </div>
                <div class="container" style="width: 82%;float: right;">

                  <%= yield %>
                </div>
              </div>
            </div>
          </div>
      <% else %>
          <div class="container">
            <%= yield %>
          </div>
      <% end %>
    </main>
  </body>

</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name,"姓名" %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :phone,"电话" %><br>
    <%= f.text_field :phone, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!-- <h1>编辑会员信息</h1> <%= render 'form' %> -->

<div class="container" style="max-width: 330px;margin-top: 100px;">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">编辑成员信息</h3>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th style="text-align:center;width: 70px">编号</th>
      <th style="text-align:center;width: 70px">姓名</th>
      <th style="text-align:center;width: 70px">电话</th>
      <th style="text-align:center;width: 70px">余额</th>
      <th style="text-align:center;width: 70px"></th>
      <% if current_login.id == 1 %>
          <th style="text-align:center;width: 70px"></th>
          <th style="text-align:center;width: 70px"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td style="text-align:center;width: 70px"><%= user.id %></td>
        <td style="text-align:center;width: 70px"><%= user.name %></td>
        <td style="text-align:center;width: 70px"><%= user.phone %></td>
        <td style="text-align:center;width: 70px" class="money" id=<%= user.id %>><%= user.money %></td>
        <td style="text-align:center;width: 70px"><%= link_to '明细', '/users/'+user.id.to_s %></td>
        <% if current_login.id == 1 %>
            <td style="text-align:center;width: 70px"><%= link_to '充值', '/recharge?user_id='+user.id.to_s %></td>
            <td style="text-align:center;width: 70px"><%= link_to '编辑', '/users/'+user.id.to_s+'/edit' %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<script>
    $(document).ready(function () {
        var ms = $("table.table>tbody>tr>td.money");
        var user_money = $("td#<%= current_login.id %>").text();
        var j = ms.length;
        var money = 0;
        for (var i=0;i<j;i++){
            if(ms[i].innerHTML != ""){
                a = parseFloat(ms[i].innerHTML)
                money += a;
            }
        };
        $('.badge').text(user_money);
        $('.total').text(money.toString());
        console.log(money.toString());
    });
</script>

app/views/users/new.html.erb
<!-- <h1>添加成员</h1> <%= render 'form' %> -->

<div class="container" style="max-width: 330px;margin-top: 100px;">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">添加成员</h3>
        </div>
        <div class="panel-body">
          <%= render 'form' %>
        </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<p>
  <strong>编号:</strong>
  <%= @user.id %>
</p>
<p>
  <strong>姓名:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>电话:</strong>
  <%= @user.phone %>
</p>

<table class="table">
  <thead>
  <tr>
    <th style="text-align:center;width: 70px">日期</th>
    <th style="text-align:center;width: 70px">地点</th>
    <th style="text-align:center;width: 70px">充值/消费</th>
  </tr>
  </thead>

  <tbody>
  <% @user.infos.sort{|a,b| b.date <=> a.date}.each do |info| %>
      <tr>
        <td style="text-align:center;width: 70px"><%= info.date %></td>
        <td style="text-align:center;width: 70px"><%= info.address %></td>
        <td style="text-align:center;width: 70px"><%= info.money %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<!-- <%= form_for [@user,@user.infos.build] do |f| %>
    <p><%= f.text_area :money, :size => '40x10' %> </p>
    <p><%= f.text_area :date, :size => '40x10' %> </p>
    <p><%= f.text_area :address, :size => '40x10' %> </p>
    <p><%= f.submit "Post Comment" %> </p>
<% end %> -->